### ISSUE TITLE
Upgrade without losing redirects

### ISSUE THREAD

**Issue by simoncox** [distantnative/retour-for-kirby#111]
How do I upgrade between versions (in my case between 2.0 and 2.0.1) without deleting all the redirects I have put in place? 
Could not see an upgrade process (I will be doing in manually not using Composer).

**Comment by distantnative** [comment]
I just pulled 2.0.1 and released 2.0.1 due to a critical bug. However the same logic applies:

If you don't use the options to change the location of the config file (which contains the redirect rules) or the database file (which contains the error logs), you can simply replace `site/plugins/retour` with the new version. Both, config and database, are stored outside of the plugin folder, so they will remain. Their structure also hasn't changed between 2.0 and 2.0.2 - so no need for an upgrade script or so.

**Comment by simoncox** [comment]
I downloaded 2.0.2 just a moment ago and swapped out as recommened (I have not changed any paths) and none of the 119 redirects I have in place are showing in the Retrour dashboard now.
I can see them in site/config/redirects.yml   -and when I test any of those they now show in failures.

**Comment by distantnative** [comment]
Not good... let me check why that could be

**Comment by distantnative** [comment]
What happens if you add a new redirect now via the Panel (please make a backup of your file with the 119 redirects before trying!)?

**Comment by distantnative** [comment]
I think I already figured it out. A line break slipped into the file name... 
Can you try to edit `site/plugins/retour/index.php` and edit line 16 from

<img width="570" alt="Screen Shot 2019-10-18 at 19 08 28" src="https://user-images.githubusercontent.com/3788865/67113799-b1395580-f1da-11e9-9ac5-5bf29ed9d772.png">

to 

<img width="516" alt="Screen Shot 2019-10-18 at 19 08 18" src="https://user-images.githubusercontent.com/3788865/67113806-b5657300-f1da-11e9-889a-a689c5df97fe.png">
?
(Moving the `'` up, so there is no line break in the string)

And can you confirm if it works then?

**Comment by simoncox** [comment]
Yes, that was it!  Can confirm the ' on the wrong line was breaking it. It had generated a new file: redirects.yml? that had the test redirect in. Now has gone back to the correct one. thank you!

**Comment by distantnative** [comment]
Will publish 2.0.3 with the fix right now! Thanks for helping and raising the bug.
