### ISSUE TITLE
Allow redirects for existing pages

### ISSUE THREAD

**Issue by hdodov** [distantnative/retour-for-kirby#161]
We have the case where we have a `/company/blog` page and a `/company/about-us` page, but we don't actually have (or want) a `/company` page - we want that to be a 404. The reason for this is SEO.

That's not possible with Retour, tough, because, quoting the [docs](https://distantnative.com/retour/docs):

>Only paths without existing pages or custom routes can be redirected.

I don't think that makes much sense. If you don't want an existing page to be redirected, you could just remove the redirect?

If I specify a route in `config.php` that matches the URL of a page, Kirby will put the `config.php` with higher priority. Since Retour is basically a plugin for configuring routes, I think it should follow the same pattern.

**Comment by distantnative** [comment]
I don’t think I want to support this use case, simply because it’s a performance matter: to allow redirects for existing pages, I would have to pump all redirects as routes in the main router. Having all routes checked on every page request. That slows the normal page down.

Instead, Retour hooks only into requests where the normal router has failed and runs the request through it’s own router with the redirects. So you should only feel any performance impact of Retour on those requests that you want to affect.

**Comment by hdodov** [comment]
>So you should only feel any performance impact of Retour on those requests that you want to affect.

But _is_ there a performance impact _to_ feel? Have you made benchmarks? I don't think it would be that much because:

- Realistically, you won't be having thousands of redirects
- Retour has to just parse its YAML redirects file, right? How slow is that going to be, keeping in mind that Kirby pretty much stores the _content itself_ this way

Perhaps @bastianallgeier could shed some light on this? He's done plenty of benchmarks.

---

From a UX standpoint, Retour's routes should have the highest priority since they're the only ones visible in the panel. If the user adds it, he wants it to take effect. If it does nothing, he comes to the conclusion that the plugin doesn't work.

**Comment by fvsch** [comment]
I kinda agree with @hdodov, I have this use case (some routes that match a real page that exists for technical reasons and which I want to redirect), and it's puzzling having those redirects not work. I think I opened an issue thinking Retour had a bug ^^ (#155)

On the other hand I see the concern about performance. Some sites _can_ have thousands of redirects, and at least a couple hundred is realistic for lots of sites.

> to allow redirects for existing pages, I would have to pump all redirects as routes in the main router

When defining routes manually it's possible to add a single route for the `(:all)` pattern as a catch all, do some further matching in the action function, and call `$this->next()` if not matching anything. I wonder if that would be doable here. Might be more performant to have a single route checking 200 patterns than to add 200 routes.

Other possible solutions, each with their own downsides:

1. A global setting that tells Retour to handle all requests and not just 404s, off by default.
2. When defining a route, defining if it should work on unhandled requests (default) or on all requests.

**Comment by distantnative** [comment]
I think I would like the last idea the most as it makes the user also most aware of what it does and what they want: having a toggle "route even when existing" (or some better phrasing).

I don't think the `(:all)` variant would make much of a difference with performance.

With the toggle, I could split up routes and only add those needed to the general router - and keep all others in my fallback router (as it is done so far).

**Comment by distantnative** [comment]
✅ will be in Retour 3 (which will be released around the release of Kirby 3.4 as it is based heavily on new things from 3.4)

<img width="1183" alt="Screen Shot 2020-06-13 at 22 03 21" src="https://user-images.githubusercontent.com/3788865/84578049-cd20e580-adc1-11ea-8fff-5f2e5dde95d4.png">

@hdodov and @fvsch: happy to hear your thoughts since this idea came from you two

**Comment by fvsch** [comment]
This looks great :)
