### ISSUE TITLE
Track slug changes

### ISSUE THREAD

**Issue by distantnative** [distantnative/retour-for-kirby#169]
**Easy:**
- just create redirect routes via hook once a slug change

**Ideal:**
- avoid redirect changes when slug changes multiple times
- automatically handle multilanguage

**Comment by medienbaecker** [comment]
Looking at how https://obsidian.md/ (File based knowledge base) handles this:
Maybe it would be a good idea to ask the user after a slug has been updated wether a redirect should be added.

**Comment by distantnative** [comment]
@medienbaecker For that I would have to hack the PageSlugDialog - I am not a big fan of replacing core components. 

My current idea is to collect all slug changes and display them in a separate suggestions list. Thinking of ranking, sorting them based on modified date and tracked failures that a redirect for this would actually prevent.
And then offer two-click creation for a redirect for this slug change (basically a button to open the add redirect dialog refilled).

**Comment by distantnative** [comment]
Just after submitting the comment above, I thought of that with Kirby 3.4 we will have a stable `page.changeSlug` global event being emitted. Maybe there is a way to make Retour listen to this and present a dialog to do what you suggested (though getting the dialog into the DOM will be the difficult part).

**Comment by medienbaecker** [comment]
@distantnative Maybe that's something that should be handled by Kirby itself (if at all)?

**Comment by distantnative** [comment]
@medienbaecker Kirby itself creating redirects after changing a slug? I don't think so. Kirby focuses on routing set up manually, there is no way of setting up Routes via UI (which is where Retour steps in). So it would be weird for Kirby to suddenly have this one magic use case for this feature.

**Comment by distantnative** [comment]
Looks like I have to throw out my second idea (listening on the event) - there isn't a good way to plant component globally in the DOM (also for some good reasons). So listening and especially displaying UI everywhere isn't really in the capacity of plugins.

So back to the suggestions list approach.

**Comment by medienbaecker** [comment]
@distantnative No, I meant exactly what Obsidian is doing:
"You changed a slug? Do you want me to search `(link: )` tags referencing this page and adjust them?"

**Comment by distantnative** [comment]
Oh you are talking about `(link: )` tags - maybe, I don't know. Still sounds a bit more like a plugin thing for me - and actually I would rather look at a unique ID approach than find-and-replace magic across all fields. 

But anyways, not a topic for Retour. This is about redirects - mostly for incoming external links. And while a "You just changed the slug, should we add a redirect in Retour?" dialog could be nice, this doesn't seem feasible for now. So let's think of alternatives.

**Comment by sebastiangreger** [comment]
Chiming in here, as this is a feature I miss so badly I've thought about eventually hacking together a small plugin myself, though never proceeded to think about the actual logic or design. I'd much prefer to collaborate over reinventing the wheel, if you want to take this further...

There are several issues that I repeatedly encounter when slugs are changed for a published page and the old URL returns a 404, while the correct response would be a 301 - or sometimes 302 (opening the can of worms already :zombie: ):
1. it's an SEO nightmare (for projects where that matters)
2. links from other websites break
3. Internal links from other pages break

Originally coming from Wordpress, I have always missed such a feature in Kirby (though I agree this is not core material). It's so easy for content editors to do "real-world damage" (as in lost sales, breaking established links, etc.) by simply modifying a slug...

So, my vision for such a feature: 
- once a slug is changed, the old URL is set up as a 301 forward (or, potentially configurable, as a 302)
- this could be a site-wide configuration (i.e. once it's turned on, any slug changes create the forward); I agree this should not happen opaquely in the background as a plugin default but I do not consider this a decision a single editor at a company should be making in the UI (this is of course different in a single-admin scenario).
- if a previously used slug is taken back into use, the forward would have to be removed
- endless loops would have to be avoided somehow™
- good to have an interface listing all of these and making them editable (this is why I vaguely thought about slug-archiving plugin writing the forwards into the Retour data file, even if it were not a Retour feature itself)

To take it even further, I would even desire a way to return error `HTTP 410 Gone` for deleted pages, the semantically correct alternative to 404 for deleted pages. This comes from my recent work with the Webmention spec, where deleting a page and then sending a Webmention to any pages that were linked in it notify those pages to remove a previously registered webmention (as long as the site explicitly returns a 410). This admittedly is an absolute edge case, and I don't mind doing that manually in Retour in the rare cases it's needed (["manual until it hurts"](https://indieweb.org/manual_until_it_hurts)). Just mentioning it here for the purpose of collecting ideas.

**Comment by distantnative** [comment]
Great input!

Making me tip a bit more into having an option to actually create redirects automatically, not just suggesting it in the Retour UI. Would probably still need to some UI to highlight those, so they aren't overseen in the general crowd of manual redirect routes.

So not sure yet whether they should be pumped into the general list of redirect routes.
Another take could be to actually split all of these, create a new tab called e.g. "Tracking" which the has a separate list from created routes for changed slugs (or even deleted pages). And in the backend one would merge the manual routes and the automatic routes before handing them over to the router.

And then this new tab could have three modes: off (no tracking at all), approve (routes for tracked changes are generated but have to be activated manually) and automatic ("it just works").

I actually think this separation makes a lot of sense. I think it could be good for UX, but if we consider things like  "if a previously used slug is taken back into use, the forward would have to be removed" it would ensure that we don't remove routes that were manually set up, but always only this generated by auto-tracking.

**Comment by sebastiangreger** [comment]
Yes, I agree. Separating automated redirects from those set up manually/intentionally is good UX and also makes this functionality transparent (especially if the modes can be switched in the Panel UI rather than in the config).

This functionally also solves the problem of expired links in content (the `(link: )` issue mentioned by @medienbaecker), as any expired links are forwarded correctly. I am always wary of having plugins auto-rewrite content files, as there is a risk of destroying content (in case of a bug or unexpected edge case). My personal inclination would be to keep this separate from the Retour plugin's feature, but once Retour keeps a dedicated log of these redirects it would be easy to write a script/plugin that takes care of such rewrites as a separate tool?

**Comment by distantnative** [comment]
> especially if the modes can be switched in the Panel UI rather than in the config).
Just raising the feature complexity 😆


> but once Retour keeps a dedicated log of these redirects it would be easy to write a script/plugin that takes care of such rewrites as a separate tool?
Should not be too complicated. I imagine them living in `site/config/redirects.yml` under a key like `tracked`. Simple array per item with something like `from`, `to`, `status` and `active`.

**Comment by sebastiangreger** [comment]
> Just raising the feature complexity laughing

Now that I think about it, I believe this could work analogous to `distantnative.retour.deleteAfter` - no need to have a frontend setting for such a static setting (eliminates complexity and reduces risk of undesired setup changes).

**Comment by distantnative** [comment]
I would start with a `config.php` option.
Moving all those to a UI interface for settings can still be a future feature.

**Comment by bvdputte** [comment]
> Oh you are talking about (link: ) tags - maybe, I don't know. Still sounds a bit more like a plugin thing for me - and actually I would rather look at a unique ID approach than find-and-replace magic across all fields.

To me these are 2 separate "things": unique id's would indeed help **a lot** to not have things break upon slug changes in Kirby. Not only in `(link: )`-tags, but also in templates, snippets, etc. But they won't help with the redirecting of elsewhere indexed links (e.g. in search engines). If we'ld have functionality that solves this, it would already help a lot for this use case. 

A side effect would be that previous registered slugs that were changes along the way would also redirect to the new slug, so pages won't break. But it could lead to strange situations when devs reading the code then will have to _search_ for slugs/redirects/... instead of tracking them down in the `content`-folder. That's whay it would be a very good thing to have this immutatable unique id thing into Kirby core somehow, but imho it's out of scope for this discussion?

**Comment by bvdputte** [comment]
I'ld love some kind of field too which shows the "slug history" on the page. Then you have a nice contextual overview of everything redirect-related to this page.
Ideally with the option there to delete previously set (automatically/manually) slug redirects you don't want any more.

I don't know how feasible that is?

**Comment by sebastiangreger** [comment]
> I'ld love some kind of field too which shows the "slug history" on the page. Then you have a nice contextual overview of everything redirect-related to the current page.

That would indeed be a great addition in terms of UX and transparency! ...a "slug history" of sorts. The data and editing APIs exist anyways, would just have to be rendered to the panel user.

Could this be an optional panel section to be integrated in a blueprint? Possibly part of the Retour plugin, but essentially could even be a tiny separate plugin (parsing/updating `redirects.yml` should be all it takes, better of course through Retour's own APIs to stay future-proof).

**Comment by medienbaecker** [comment]
> Could this be an optional panel section to be integrated in a blueprint? Possibly part of the Retour plugin, but essentially could even be a tiny separate plugin (parsing/updating redirects.yml should be all it takes, better of course through Retour's own APIs to stay future-proof).

That's a great idea. Retour could also come with a field that displays **and** saves the slugs on the page itself. With status icons and one-click redirection taking you to the Retour panel view.

**Comment by distantnative** [comment]
Uiuiui... I do like the idea of a blueprint section. So far I didn't really plan to keep a log of slug history though but only the current state of redirect rules, e.g. when

A ->B
B -> C
C -> D

then only store the rule

A -> D

**Comment by bvdputte** [comment]
I think if the goal for adding this is to prevent "link rot" you have no other option then to also store the "intermediary" slugs because they can be indexed in search engines or saved in bookmarks, or linked from newsletters, ...

If you only keep "a" and redirect that to the latest known, e.g. "d", then if people visit "b" directly they'll get a 404, which is not what you want to solve with this?

**Comment by bvdputte** [comment]
I think another hard part is reacting on Kirby that will allow to generate a slug for something that is now available, but existed already in the past and is already in the redirects. 

How would you handle this?

**Comment by sebastiangreger** [comment]
Uh-oh, this is a much bigger can of worms than at first sight... :speak_no_evil: 

Out of curiosity, I ran a quick benchmark on Wordpress: they use HTTP 301. The way it is done is that on a slug change, a field `_wp_old_slug` is attached to the `postmeta` table. When a URL does not exist, the WP engine checks for any current pages that have a corresponding old slug meta filed attached. This of course only works because they use unique IDs; in the case of Kirby the equivalent would be a custom field in content files, which is not an option.

Since Kirby does not auto-ID pages, having such metadata stored centrally is tricky. I encountered this when working on the Commentions plugin -- which is why we went for attaching all plugin's data to the content's folders (we use a `_commentions` subfolder in the page's folder, containing the data). Physically attaching the "old slugs" to the content folder on a file level (analogous to the Wordpress way) would have the benefit of always staying with the content. It would however break with the logic and simplicity of the Retour plugin (which currently is based on URLs, not pages, so can be served by a centralised data file in the `config` folder without issues) and likely have performance implications for huge sites; also, there are [no canonical rules](https://github.com/getkirby/ideas/issues/304) regarding plugin data storage.

Some other random considerations:
1. When going with centralised storage without unique IDs, the hooks and attached routines have to do all the heavy lifting to keep the data up-to-date; this is fine as long as the Panel is used, but as soon as URLs are renamed in the file system, things become nasty. It's one thing that the automatic redirects are not created when not using the panel (a fair limitation), but it's of course another thing if Retour's data starts to be out of sync with reality (redirects stored from Panel-based slug changes, followed by manual changes to folder names).
2. No need to track slug changes while pages are in draft (stating the obvious :wink: )
3. @bvdputte already covered this one: if a previously assigned URL is taken into use for a new page, how does the plugin make sure the old forward is deleted; or should there even be a warning (likely impossible to achieve without replacing the core "change URL" component)? After all, once a "301 Moved permanently" has been issued, it can be assumed that Google for example (also, afaik, some browser caches) will eternally connect that URL with its redirect target; it's essentially "burnt".
4. Risk scenario: admin wants to turn a previously listed page into an unlisted page at an unknown URL, therefore changes page status to `unlisted` and changes slug (security by obscurity). The old public URL should not redirect. On the other hand, the change from listed to unlisted could be simply to hide it from a list of pages, hence both keeping it publicly available and forward the old URL would be desired. Depending on the mental model of the admin user, either default behaviour could be surprising.
5. (Only relevant as of Kirby 3.5) How about moved pages? Moving a page from `/blog/news/xyz` to `/blog/archive/xyz` is not a slug change, but would still call for a redirect. If we think of moving a page as a simple editorial act, I believe this could be considered in scope; if we think of it as "redesigning" a site's structure, it is out of scope and a case for a classic manual Retour redirect.

**Comment by distantnative** [comment]
I think we have to establish a baseline here:
Based on all your own explanations, there is no way Retour turns into magic that "just works". Simply because there isn't such a thing. For the same context and actions, you might still want different things to happen. And that for a case by case decision. So there is no automatic way that excludes editors completely. 

Retour can only help with maintenance. It can't make the decisions.

Second baseline: Any tracking feature will only work when using the Panel (or PHP API). Changes in the filesystem itself cannot happen. It's as simple.

Regarding the unique ID things, I am not sure if I grasped the issue:

If I have the actions

notes/a-sunny-day -> notes/the-sunniest-day
notes/the-sunniest-day -> notes/the-sunniest-day-in Europe

I would want redirects tracked/created for

notes/a-sunny-day -> notes/the-sunniest-day-in Europe
notes/the-sunniest-day -> notes/the-sunniest-day-in Europe

In that sense, I am not really dealing with pages here and I don't care as much what the page is. I get info about slugs (and more precisely full IDs) through hooks. Mainly `changeSlug` which gives me a new one and an old one. And base don these the hooks have to do some logic.

If a new page `notes/a-sunny-day` gets added. The first redirect would have to be deleted. I don't think it's in the scope of any plugin to figure out how the Google cache reacts to that, those are decisions beforehand, that an admin needs to take: will I ever reuse URLs again? Then maybe 301 isn't the best idea.

But while I am writing that, I realize that this is getting even more complex: subpages. If

notes -> blog

happens, what should this have as consequences. So many cases to cover.

I was getting excited but am not so sure anymore about the idea and what can be done.

**Comment by distantnative** [comment]
Oh and also: storing that data with the pages is not really an option, I think. Sounds like we would need to read the content files of all files for each request.

**Comment by sebastiangreger** [comment]
Yes, that's how I see this as well, after originally thinking "this should be a straightforward thing to tackle some day") :rofl:

I fully agree: no implementation (within Retour or even a separate, highly specialized plugin) would ever be able to cover every condition. I still imagine the baseline functionality could be a worthwhile addition to Retour:
1. when changing a slug via Panel/API, an automated rule is created
2. since they are accessible through the Panel, any maintenance (like removing etc.) can be done by the admin manually; essentially rendering this functionality more of an "assistant" rather than a "fire and forget" kind of tool.
3. If an old URL gets used again, its redirect is removed or simply ignored

From my experience, that would cover 99% of the issues I've had with client sites in the past -- it's almost always about "we fixed a typo in the URL", two days after promoting it on all the social media channels.

> Regarding the unique ID things, I am not sure if I grasped the issue [...] In that sense, I am not really dealing with pages here and I don't care as much what the page is.

I hadn't looked at it this way; this can indeed be treated as a purely URL-based operation once the thought of "covering all and any edge cases" is replaced with a realistic baseline of just assisting in tracking altered slugs.

> But while I am writing that, I realize that this is getting even more complex: subpages.

:exploding_head:

**Comment by bvdputte** [comment]
> If I have the actions
> 
> notes/a-sunny-day -> notes/the-sunniest-day
> notes/the-sunniest-day -> notes/the-sunniest-day-in Europe
> 
> I would want redirects tracked/created for
> 
> notes/a-sunny-day -> notes/the-sunniest-day-in Europe
> notes/the-sunniest-day -> notes/the-sunniest-day-in Europe

👍 Indeed, that would already cover 99% of the cases I think. In my experience, top-level pages are _usually_ set by the dev and don't change slugs often.

**Comment by tobscheeder** [comment]
I found a maybe unwanted behaviour in a multilanguage setup.

When the slug is changed in any language, the redirect is configured to the default language.

Like:
en/notes/a-sunny-day -> de/notes/the-sunniest-day

**Comment by distantnative** [comment]
@tobscheeder this features hasn't been implemented yet, so I am not sure what you are referring to.

If you encounter an issue with the release, please open a separate issue.
If that's a comment on the suggested ideas, I'm not sure I understand it fully yet.
