### ISSUE TITLE
Possible line length bug (or user error!)

### ISSUE THREAD

**Issue by steveabraham** [distantnative/retour-for-kirby#244]
## Describe the bug
I've added a few directs required after a site re-launch. Shortly after I spotted that the redirects were not working, and upon inspecting the redirects.yml file, I've noticed "corruptions" on some of the lines.

It appears that longer lines are being wrapped:
<img width="533" alt="Screenshot 2021-05-04 at 09 11 16" src="https://user-images.githubusercontent.com/201684/116976620-516da700-acb9-11eb-8916-a4349692dece.png">
If I repair this manually, everything works again for a few moments and then breaks again.

## Specifications

  - Retour version: 3.0.1
  - Retour config options: None
  - Kirby version: 3.5.3.1
  - Browser: Latest Safari, Latest Chrome, Private Browser Window

**Comment by distantnative** [comment]
This hopefully is solved by Retour 4.0 - [first beta](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1). Please help me test the beta, so that we can make sure that the actual release works intended.

Thanks for your patience with this, I know it has been a pain point for many months.
