### ISSUE TITLE
Redirects disappearing unexpectedly after a while

### ISSUE THREAD

**Issue by anta199** [distantnative/retour-for-kirby#249]
Hello,
First of all, thanks for the work put on this plugin.

I've been encountering an issue where I set a redirect, that seems to work for a while, before disappearing from the listed redirects list and therefore stops to work.

## Steps to reproduce

  1. Set a redirect in the panel via Retour
  2. Works for a while
  3. Re-check after a few hours to see it's not there anymore

## Expected behavior
Redirects staying and working indefinitely as they are set in the panel.

## Additional context
https://ibb.co/Gkhg8jB
https://ibb.co/9rD7Qx7

## Specifications

  - Retour version: 3.0.1
  - Kirby version: 3.5.4
  - Browser: Google Chrome 91.0.4472.114 (Build oficial) (x86_64) on Macbook Pro

**Comment by fvsch** [comment]
Wondering if this is the same as #229. Can you check your `redirects.yml` file?

**Comment by distantnative** [comment]
This hopefully is solved by Retour 4.0 - [first beta](https://github.com/distantnative/retour-for-kirby/releases/tag/4.0.0-beta.1). Please help me test the beta, so that we can make sure that the actual release for sure doesn't suffer from the same problems as Retour 3 did.

Thanks everyone for your patience with this, I know it has been a pain point for many months.
