### ISSUE TITLE
Allow change of menu item.

### ISSUE THREAD

**Issue by louiswalch** [distantnative/retour-for-kirby#59]
It would be nice to be able to change the "Retour" menu item added to Kirby Panel. I'd prefer if this said "Redirects" or something more simple for my clients.

**Comment by distantnative** [comment]
That's a tricky one since the name is hardcoded in the Javascript files and gets loaded and used by the Panel before ever communicating with the PHP core/API/backend where such an option could be set.

The thing to consider for me is if at least the menu item indeed gets a simpler name like "Redirects" and Retour stays the name of the plugin and on the plugin view the headline. I'm a bit torn as the plugin not only covers redirects but also the error tracking. Then again I get that it might be not the most obvious term for clients.

**Comment by louiswalch** [comment]
Thanks @distantnative, I am glad you are open to the suggestion. I can see how you want to enforce your branding for the product, but agree it belongs more on the actual page.

**Comment by distantnative** [comment]
I looked into it, but Kirby doesn't actually allow to separate name from menu label string. So for now, I will leave it as Retour.
