### ISSUE TITLE
Multilingual sites

### ISSUE THREAD

**Issue by nilshoerrmann** [distantnative/retour-for-kirby#85]
Retour seems to have problems handling multilingual sites:
when I enter a site at `/` and Kirby redirects me to `/de` as it should, Retour is logging this as a failed request.

This is happening on Kirby 3.2.1-rc.1.

**Comment by nilshoerrmann** [comment]
It's seems that Retour is actually considering all URLs with a language key as non-existent.

**Comment by distantnative** [comment]
I just checked it and it seems to work as intended:

Redirect `test` to `about` leads to `de/about` without logging a fail.
But you need to setup individual redirects per language if you want `de/test` and `en/Test` to be caught. Since translated slugs per language are very common, this seems better than automatically redirecting slugs in al languages (which is also very tricky to implement).

**Comment by mxdvl** [comment]
I am actually seeing all language urls as failures somehow… which is not correct as these urls do not return a 404 error page, they exist!

![image](https://user-images.githubusercontent.com/76776/76505431-5f22f600-6441-11ea-99fc-47bac5f8e2c1.png)

Is there any option to enable debugging?
